# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LBWeChat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LBWeChat
pod "SDWebImage"
pod "MJRefresh"
pod "FMDB"
pod "MLLabel"
#pod "AMap3DMap"
pod "UMengAnalytics-NO-IDFA"
#pod "MMWebView"
pod "UUButton"
pod "UUActionSheet"
end
